### ISSUE TITLE
Plugin name convention?

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-register-timeout#4]
What is `plugin.name` https://github.com/fastify/fastify-register-timeout/blob/master/index.js#L19 the function name ?
This should be documented in the readme.

**Comment by allevo** [comment]
`plugin.name` is described [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name)

**Comment by StarpTech** [comment]
I mean you should document this because its not required for plugin registration and users will get an error message like `'Timeout reached:`. The function name should be required and checked at initializing.

**Comment by allevo** [comment]
Closed by #7
